name = "cs-report-worker"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cs-report-db"
database_id = "1ee13c57-c125-4b49-9a6c-88f38b2f80ec"

# 环境变量
[vars]
FROM_EMAIL = "noreply@your-domain.com"

# 生产环境密钥（通过 wrangler secret put 设置）
# EMAIL_API_KEY = "your-email-api-key"

# 路由配置 - 自定义域名
[[routes]]
pattern = "csreport-api.20990909.xyz/*"
zone_name = "20990909.xyz"

# 开发环境配置
[env.development]
name = "cs-report-worker-dev"

[env.development.vars]
FROM_EMAIL = "dev@your-domain.com"
